### ISSUE TITLE
[버그] webpack, express 환경 설정

### ISSUE THREAD

**Issue by minsu-zip** [woowa-techcamp-2022/web-moneybook-04#2]
# 🔨 버그 설명

express 설정 에러

# 📑 해결 방안
// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404))
})

에러 핸들러 순서 변경 및 폴더 구조 변경으로 문제 해결

**Comment by Zih0** [comment]
**페어 프로그래밍 결정사항**

에러 핸들링 관련 코드는 일단 제거하기로 결정했고, 추후에 필요할 때 기존 `express generator`에서 설정해준 방식이 아닌,
직접 원하는 에러핸들링을 넣는 방향으로.

**Comment by Zih0** [comment]
# file-loader

webpack v5 이후, 에셋 모듈을 지원하게 되었다.
`file-loader`, `url-loader` 사용을 지양하고 `asset-modules`을 사용하도록 하자

https://webpack.kr/guides/asset-modules/
